-- Create the database
CREATE DATABASE DEVELOPMENT_DB AUTOMATIC STORAGE YES USING CODESET UTF-8 TERRITORY US PAGESIZE 32768;

-- Connect to the database
CONNECT TO DEVELOPMENT_DB;

-- Create a schema
CREATE SCHEMA MYSCHEMA;

-- Set current schema
SET SCHEMA MYSCHEMA;

-- Create your tables
CREATE TABLE EMPLOYEES (
    EMP_ID INTEGER NOT NULL PRIMARY KEY,
    FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(100),
    HIRE_DATE DATE,
    SALARY DECIMAL(10,2),
    DEPARTMENT VARCHAR(50)
);

-- Insert sample data
INSERT INTO EMPLOYEES VALUES 
(1, 'John', 'Doe', 'john.doe@example.com', '2024-01-15', 75000.00, 'Engineering'),
(2, 'Jane', 'Smith', 'jane.smith@example.com', '2024-02-20', 82000.00, 'Marketing');

-- Grant privileges
GRANT ALL ON TABLE MYSCHEMA.EMPLOYEES TO PUBLIC;

CONNECT RESET;