-- Create the database
-- CREATE DATABASE DEVDB AUTOMATIC STORAGE YES USING CODESET UTF-8 TERRITORY US PAGESIZE 32768;

-- Connect to the database
-- CONNECT TO DEVDB;

-- -- Create a schema
-- CREATE SCHEMA sail;

SET SCHEMA sail;

CREATE TABLE GP_EVENT_REFORMATTED (
    ALF_E BIGINT NOT NULL,
    ALF_STS_CD CHAR(10) NOT NULL,
    ALF_MTCH_PCT DECIMAL(5,2) NOT NULL,
    PRAC_CD_E INT NOT NULL,
    EVENT_CD_ID INT NOT NULL,
    EVENT_VAL DECIMAL(10,2) NOT NULL,
    EVENT_DT DATE NOT NULL,
    EVENT_YR SMALLINT NOT NUL);

CREATE TABLE GP_EVENT_CODES (
    EVENT_CD_ID INT NOT NULL,
    EVENT_CD SMALLINT NOT NULL,
    IS_READ_V2 SMALLINT NOT NULL,
    IS_READ_V3 SMALLINT NOT NULL,
    IS_VALID_CODE SMALLINT NOT NULL,
    DESCRIPTION VARCHAR(200) NOT NULL,
    EVENT_TYPE CHAR(20) NOT NULL,
    HIERARCHY_LEVEL_1 VARCHAR(50) NOT NULL,
    HIERARCHY_LEVEL_1_DESC VARCHAR(200) NOT NULL,
    HIERARCHY_LEVEL_2 VARCHAR(50) NOT NULL,
    HIERARCHY_LEVEL_2_DESC VARCHAR(200) NOT NULL,
    HIERARCHY_LEVEL_3 VARCHAR(50) NOT NULL,
    HIERARHCY_LEVEL_3_DESC VARCHAR(200) NOT NULL);

CREATE TABLE GP_EVENT_CLEANSED (
    PRAC_CD_PE INTEGER NOT NULL,
    LOCAL_NUM_PE BIGINT NOT NULL,
    EVENT_CD_VRS CHAR(10) NOT NULL,
    EVENT_CD CHAR(20) NOT NULL,
    EVENT_VAL DECIMAL(10,2) NOT NULL,
    EVENT_DT DATE NOT NULL,
    EPISODE CHAR(20) NOT NULL,
    SEQUENCE INTEGER NOT NULL,
    DELTA_KEY CHAR(1) NOT NULL,
    BATCH_NUM SMALLINT NOT NULL,
    EVENT_YR SMALLINT NOT NULL,
    CREATE_DT DATE NOT NULL,
    AVAIL_FROM_DT DATE NOT NULL,
    SOURCE_EXTRACT INTEGER NOT NULL
);

CREATE TABLE PATIENT_ALF_CLEANSED (
    WOB DATE NOT NULL,
    PRAC_CD_PE INTEGER NOT NULL,
    DELTA_KEY CHAR(1) NOT NULL,
    LOCAL_NUM_PE INTEGER NOT NULL,
    ALF_STS_CD CHAR(10) NOT NULL,
    ALF_PE BIGINT NOT NULL,
    ALF_MTCH_PCT DECIMAL(5,2) NOT NULL,
    LSOA_CD CHAR(15) NULL,
    BATCH_NUM SMALLINT NOT NULL,
    PROCESS_DT DATE NOT NULL,
    CREATE_DT DATE NOT NULL,
    AVAIL_FROM_DT DATE NOT NULL,
    OPT_OUT_FLG CHAR(1) NOT NULL,
    SOURCE_EXTRACT INTEGER NOT NULL,
    GNDR_CD CHAR(1) NOT NULL,
    REG_CAT_CD CHAR(10) NOT NULL);

CREATE TABLE WLGP_CLEANED_GP_REG_BY_PRACINCLUNONSAIL_MEDIAN (
    ALF_PE INTEGER NOT NULL,
    AVAILABLE_FROM TIMESTAMP NOT NULL,
    END_DATE DATE NOT NULL,
    GP_DATA_FLAG INTEGER NOT NULL,
    PRAC_CD_PE INTEGER NOT NULL,
    START_DATE DATE NOT NULL);

CREATE TABLE WLGP_CLEANED_GP_REG_MEDIAN (
    ALF_PE INTEGER NOT NULL,
    AVAILABLE_FROM TIMESTAMP NOT NULL,
    END_DATE DATE NOT NULL,
    GP_DATA_FLAG INTEGER NOT NULL,
    START_DATE DATE NOT NULL);

-- Grant privileges
-- GRANT ALL ON TABLE SAIL.gp_event_reformatted TO PUBLIC;
-- GRANT ALL ON TABLE SAIL.gp_event_codes TO PUBLIC;

CONNECT RESET;